- name: Install pipx
  ansible.builtin.package:
    name: pipx
    state: present

- name: Install python packages with pipx globally
  ansible.builtin.command:
    cmd: "pipx install {{ item.apt | default(item.name) }}"
    creates: "/usr/local/bin/{{ item.apt | default(item.name) }}"
  environment:
    PIPX_HOME: /opt/pipx
    PIPX_BIN_DIR: /usr/local/bin
  loop: "{{ package_list_pip | default([]) | union(package_list_host_pip | default([])) | union(package_list_group_pip | default([])) | unique }}"
  become: true

