---

- name: install snapd
  apt:
    name:
      - snapd
    update_cache: true

- name: ensure snap service is running
  service:
    name: snapd
    state: started
    enabled: true

- name: Install snap packages
  snap:
    name: "{{ item.name }}"
    classic: "{{ item.use_classic | default(false) }}"
    channel: "{{ item.channel | default('stable') }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ package_list_snap + package_list_host_snap + package_list_group_snap}}"
